FROM ubuntu:22.04

# 设置环境变量
ENV DEBIAN_FRONTEND=noninteractive

# 安装 GCC 和构建工具
RUN apt-get update && \
    apt-get install -y \
    gcc \
    g++ \
    binutils-arm-none-eabi\
    gdb-arm-none-eabi\
    gcc-arm-none-eabi


# 验证安装
RUN gcc --version && g++ --version

WORKDIR /workspace
CMD ["/bin/bash"]