FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    gcc \
    g++ \
    binutils-arm-none-eabi\
    gdb-arm-none-eabi\
    gcc-arm-none-eabi\
    cmake\
    git\
    openocd



RUN gcc --version && g++ --version

WORKDIR /workspace
CMD ["/bin/bash"]